import { TEvent } from "@/assets/types/Components/TEvent";
import {
  event1,
} from "@/assets/images";

export const eventsMock: TEvent[] = [
  {
    id: 1,
    title: "PENGUKUHAN IBU APIATY AMIN SYAM",
    content:
      "PADA HARI SENIN, 15 JANUARI 2024 PADUAN SUARA MAHASISWA UNIVERSITAS HASANUDDIN TELAH DIBERIKAN KEPERCAYAAN UNTUK TAMPIL PADA ACARA “PENGUKUHAN IBU APIATY AMIN SYAM” YANG DILAKSANAKAN DI CLARO HOTEL MAKASSAR.",
    image: event1,
  },
  {
    id: 2,
    title: "PENGUKUHAN IBU APIATY AMIN SYAM",
    content:
      "PADA HARI SENIN, 15 JANUARI 2024 PADUAN SUARA MAHASISWA UNIVERSITAS HASANUDDIN TELAH DIBERIKAN KEPERCAYAAN UNTUK TAMPIL PADA ACARA “PENGUKUHAN IBU APIATY AMIN SYAM” YANG DILAKSANAKAN DI CLARO HOTEL MAKASSAR.",
    image: event1,
  },
  {
    id: 3,
    title: "PENGUKUHAN IBU APIATY AMIN SYAM",
    content:
      "PADA HARI SENIN, 15 JANUARI 2024 PADUAN SUARA MAHASISWA UNIVERSITAS HASANUDDIN TELAH DIBERIKAN KEPERCAYAAN UNTUK TAMPIL PADA ACARA “PENGUKUHAN IBU APIATY AMIN SYAM” YANG DILAKSANAKAN DI CLARO HOTEL MAKASSAR.",
    image: event1,
  },
];
